Update Makefile
The port is incremented by 1 and then checked again until an unused port is found avoiding this way error due port 9001 already being used. 

Error: listen EADDRINUSE 0.0.0.0:9001
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:141:18)
    at node.js:933:3